import { Footer } from "@/frontend/components/footer/Footer";
import Header from "@/frontend/components/header/Header";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Book Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
