import { Footer } from "@/frontend/components/footer/Footer";
import SessionProvider from "@/frontend/components/auth/SessionProvider";
import HeaderWithSession from "@/frontend/HeaderWithSession/HeaderWithSession";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Book Tracker",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <HeaderWithSession /> {/* Client header with session */}
        {children}
        <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
